### ISSUE TITLE
프론트 - [헤더] 로그아웃

### ISSUE THREAD

**Issue by joong8812** [4-in-dev/RoutineWave-Frontend#10]
### 작업내용
* 헤더 네비게이션 바에 `로그아웃` 버튼을 누르면 로그아웃이 된다.
* 로그아웃이 된 이후에는 로그인 페이지로 간다

### 궁금 포인트
* 로그아웃 이후에 `access_token`을 담고 있는 `is_login` 쿠키를 삭제해야 할까?

**Comment by iamdoerchoi** [comment]
* 우선 궁금포인트는 나중에 생각해보자
